// All provider responses in this suite are MOCKS; no actual authorization is performed.
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {createServer} from '../../lib/lume-server.mjs';
const secret='MOCK_LONG_TOKEN_DO_NOT_EXPOSE';
async function fixture(fn){const dir=await mkdtemp(tmpdir()+'/lume-test-');let clock=Date.now();const calls=[];const env={META_APP_ID:'123',META_APP_SECRET:'MOCK_SECRET',PUBLIC_BASE_URL:'https://example.com',TOKEN_ENCRYPTION_KEY:'ab'.repeat(32),DATA_DIR:dir};
const provider=async(input,init={})=>{const u=new URL(input);calls.push({u,init});let data={};if(u.hostname==='api.instagram.com')data={data:[{access_token:'MOCK_SHORT',user_id:'42'}]};else if(u.pathname==='/access_token')data={access_token:secret,expires_in:5184000};else if(u.pathname.endsWith('/me')||u.pathname.endsWith('/42'))data={id:'42',user_id:'42',username:'mock_user',followers_count:123,media_count:1};else if(u.pathname.endsWith('/media'))data={data:[{id:'99',media_type:'IMAGE',media_product_type:'FEED',timestamp:new Date(clock-86400000).toISOString(),caption:'Mock post',permalink:'https://www.instagram.com/p/mock/'}]};else if(u.pathname.endsWith('/insights')){const m=u.searchParams.get('metric');if(m==='views')return new Response(JSON.stringify({error:{code:10,message:secret}}),{status:400});data={data:m==='saved'?[]:[{name:m,total_value:{value:10},values:[{value:10,end_time:new Date(clock).toISOString()}]}]};}return new Response(JSON.stringify(data));};
let server,base;async function start(){server=createServer(env,{fetch:provider,now:()=>clock});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;}await start();const request=(p,options={})=>fetch(base+p,{redirect:'manual',...options});const begin=async()=>{const r=await request('/api/auth/start?provider=instagram');assert.equal(r.status,302);return {cookie:r.headers.get('set-cookie').split(';')[0],state:new URL(r.headers.get('location')).searchParams.get('state'),r};};try{await fn({env,dir,calls,request,begin,advance:n=>clock+=n,restart:async()=>{await new Promise(r=>server.close(r));await start();}});}finally{await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});}}
test('MOCK OAuth binds expiring one-use state to secure browser session',()=>fixture(async({begin,request,calls,advance})=>{const a=await begin(),b=await begin();assert.match(a.r.headers.get('set-cookie'),/HttpOnly/);assert.match(a.r.headers.get('set-cookie'),/Secure/);assert.match(a.r.headers.get('set-cookie'),/SameSite=Lax/);let r=await request(`/auth/instagram/callback?state=${a.state}&code=mock`,{headers:{cookie:b.cookie}});assert.match(r.headers.get('location'),/error=invalid_state/);assert.equal(calls.length,0);r=await request(`/auth/instagram/callback?state=${a.state}&code=mock`,{headers:{cookie:a.cookie}});assert.equal(r.headers.get('location'),'/?connected=1');r=await request(`/auth/instagram/callback?state=${a.state}&code=mock`,{headers:{cookie:a.cookie}});assert.match(r.headers.get('location'),/invalid_state/);const c=await begin();advance(601000);r=await request(`/auth/instagram/callback?state=${c.state}&code=mock`,{headers:{cookie:c.cookie}});assert.match(r.headers.get('location'),/invalid_state/);}));
test('MOCK persistence encrypted, restart ownership, isolated data and CSRF',()=>fixture(async({begin,request,dir,restart})=>{const a=await begin();await request(`/auth/instagram/callback?state=${a.state}&code=mock`,{headers:{cookie:a.cookie}});const disk=await readFile(dir+'/store.enc','utf8');assert.ok(!disk.includes(secret)&&!disk.includes('mock_user')&&!disk.includes(a.cookie.split('=')[1]));await restart();let r=await request('/api/config',{headers:{cookie:a.cookie}});assert.equal((await r.json()).connected,true);r=await request('/api/dashboard?account=42&days=7');assert.equal(r.status,404);r=await request('/api/dashboard?account=42&days=7',{headers:{cookie:a.cookie}});const text=await r.text();assert.ok(!text.includes(secret));const d=JSON.parse(text);assert.equal(d.metrics.followers,123);assert.equal(d.metrics.views,null);assert.equal(d.content[0].saved,null);assert.ok(d.errors.some(e=>e.metric==='views'));assert.equal((await request('/api/disconnect?account=42',{method:'POST',headers:{cookie:a.cookie,origin:'https://evil.test'}})).status,403);assert.equal((await request('/api/disconnect?account=42',{method:'POST',headers:{cookie:a.cookie,origin:'https://example.com'}})).status,200);assert.equal((await (await request('/api/config',{headers:{cookie:a.cookie}})).json()).connected,false);}));
test('MOCK cross-owner POST denied, sync cooldown and cancellation consume state',()=>fixture(async({begin,request,calls})=>{const a=await begin(),b=await begin();await request(`/auth/instagram/callback?state=${a.state}&code=mock`,{headers:{cookie:a.cookie}});for(const path of ['/api/dashboard','/api/sync','/api/disconnect']){const r=await request(path+'?account=42',{method:path==='/api/dashboard'?'GET':'POST',headers:{cookie:b.cookie,origin:'https://example.com'}});assert.equal(r.status,404);}const headers={cookie:a.cookie,origin:'https://example.com'};assert.equal((await request('/api/sync?days=7',{method:'POST',headers})).status,200);assert.equal((await request('/api/sync?days=7',{method:'POST',headers})).status,429);const count=calls.length;const denial=await request(`/auth/instagram/callback?state=${b.state}&error=access_denied&error_description=DO_NOT_ECHO`,{headers:{cookie:b.cookie}});assert.equal(denial.headers.get('location'),'/?error=authorization_denied');const replay=await request(`/auth/instagram/callback?state=${b.state}&code=mock`,{headers:{cookie:b.cookie}});assert.equal(replay.headers.get('location'),'/?error=invalid_state');assert.equal(calls.length,count);}));
test('OAuth throttles repeated authorization starts',()=>fixture(async({request})=>{for(let i=0;i<10;i++)await request('/api/auth/start?provider=instagram');assert.equal((await request('/api/auth/start?provider=instagram')).status,429);}));
