// Unit tests with MOCK Instagram HTTP responses. Not evidence of real consent or API access.
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {Store,encryptionKey} from '../../lib/backend/store.mjs';
import {Instagram,collect,aggregate} from '../../lib/backend/instagram.mjs';
const now=Date.now(),json=x=>new Response(JSON.stringify(x));
const conn=()=>({id:'42',token:'MOCK_TOKEN',tokenIssuedAt:now-2*86400000,expiresAt:now+60*86400000,profile:{username:'mock'}});
test('encrypted store authenticates ciphertext and rejects wrong keys; strict key validation',async()=>{const dir=await mkdtemp(tmpdir()+'/lume-store-');try{assert.equal(encryptionKey('bad'),null);assert.equal(encryptionKey('!'.repeat(44)),null);assert.equal(encryptionKey(Buffer.alloc(32).toString('base64')).length,32);const key=Buffer.alloc(32,1);new Store(dir,key);assert.throws(()=>new Store(dir,Buffer.alloc(32,2)),/STORE_UNAVAILABLE/);const raw=JSON.parse(await readFile(dir+'/store.enc','utf8'));raw.data=Buffer.alloc(60).toString('base64');await writeFile(dir+'/store.enc',JSON.stringify(raw));assert.throws(()=>new Store(dir,key),/STORE_UNAVAILABLE/);}finally{await rm(dir,{recursive:true,force:true});}});
test('MOCK exchange uses documented endpoints, scopes kept server-side and both token formats supported',async()=>{for(const wrapped of [false,true]){const calls=[];const api=new Instagram({META_APP_ID:'123',META_APP_SECRET:'MOCK_APP_SECRET',PUBLIC_BASE_URL:'https://example.com'},async(u,init)=>{calls.push({u:new URL(u),init});return json(calls.length===1?(wrapped?{data:[{access_token:'MOCK_SHORT'}]}:{access_token:'MOCK_SHORT'}):{access_token:'MOCK_LONG',expires_in:5000});});assert.equal((await api.exchange('MOCK_CODE')).access_token,'MOCK_LONG');assert.equal(calls[0].u.href,'https://api.instagram.com/oauth/access_token');assert.equal(calls[0].init.body.get('redirect_uri'),'https://example.com/auth/instagram/callback');assert.equal(calls[0].init.body.get('code'),'MOCK_CODE');assert.equal(calls[1].u.searchParams.get('grant_type'),'ig_exchange_token');assert.equal(calls[1].init.redirect,'error');}});
test('MOCK 90-day unique metrics are null; separate compatible Story metrics, bounded calls and content',async()=>{const calls=[];const api=new Instagram({},async u=>{u=new URL(u);calls.push(u);if(u.pathname.endsWith('/42'))return json({followers_count:50});if(u.pathname.endsWith('/media'))return json({data:Array.from({length:25},(_,i)=>({id:String(100+i),timestamp:new Date(now-86400000).toISOString(),media_product_type:i===0?'STORY':'FEED',media_type:'IMAGE'})),paging:{next:'https://evil.example/token-leak',cursors:{after:'cursor'}}});const metric=u.searchParams.get('metric');return json({data:[{name:metric,total_value:{value:10}}]});});const r=await collect(api,conn(),90,now);assert.equal(r.metrics.reach,null);assert.equal(r.metrics.accountsEngaged,null);assert.equal(r.metrics.views,30);assert.equal(r.truncated,true);assert.equal(r.partial,true);assert.ok(r.content.length<=12);assert.ok(calls.length<=100);assert.ok(calls.every(u=>u.hostname==='graph.instagram.com'));const story=calls.filter(u=>u.pathname.endsWith('/100/insights'));assert.ok(story.every(u=>!['likes','comments','saved'].includes(u.searchParams.get('metric'))));assert.ok(calls.filter(u=>u.pathname.endsWith('/insights')).every(u=>!u.searchParams.get('metric').includes(',')));assert.equal(aggregate([r,r]).reach,null);});
test('MOCK expired tokens do not fetch and unavailable/empty provider data is never zero',async()=>{let count=0;const api=new Instagram({},async()=>{count++;return json({data:[]});});const expired=conn();expired.expiresAt=now-1;const e=await collect(api,expired,7,now);assert.equal(count,0);assert.equal(e.metrics.followers,null);assert.equal(e.errors[0].code,'token_expired');const r=await collect(api,conn(),7,now);assert.equal(r.metrics.views,null);assert.equal(r.metrics.reach,null);assert.ok(r.errors.some(e=>e.code==='metric_unavailable'));});
test('MOCK near-expiry tokens refresh server-side; provider errors sanitized',async()=>{let refreshed=false;const api=new Instagram({},async u=>{u=new URL(u);if(u.pathname==='/refresh_access_token'){refreshed=true;assert.equal(u.searchParams.get('grant_type'),'ig_refresh_token');return json({access_token:'MOCK_REFRESHED',expires_in:5184000});}return new Response(JSON.stringify({error:{code:190,message:'SECRET MUST NOT LEAK'}}),{status:400});});const c=conn();c.expiresAt=now+86400000;const r=await collect(api,c,7,now);assert.equal(refreshed,true);assert.equal(c.token,'MOCK_REFRESHED');assert.ok(!JSON.stringify(r).includes('SECRET'));assert.ok(r.errors.some(e=>e.code==='token_expired'));});
